In [2]:
#using python as a calculator
3+5*4

23

In [3]:
weight_kg = 60 

In [4]:
print(weight_kg)

60


In [5]:
print(weight_kg*weight_kg)

3600


In [7]:
my_number = 3
my_float = 2.434 
my_string = "this is my floating point number: "

In [8]:
print (my_string, my_float)

this is my floating point number:  2.434


In [13]:
weight_kg_text = 'weight in kilograms:'
print(weight_kg_text, weight_kg)
print('weight in pounds:', weight_kg * 2.2)
print(weight_kg)
weight_kg = 100
print(weight_kg)

weight in kilograms: 100
weight in pounds: 220.00000000000003
100
100


In [14]:
x = 5 
y = 6 
print(x+y)

11


In [15]:
x = y
print(x+y)

12


In [16]:
mass = 47.5
age = 122
mass = mass *2.0
age = age - 20
print(mass, age)

95.0 102


In [17]:
first, second = 'Grace', 'Shawn'
third, fourth = second, first
print(third, fourth)

Shawn Grace


In [18]:
import numpy

In [19]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [20]:
medical_data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [21]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [22]:
import numpy as np

In [23]:
medical_data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [30]:
print(type(medical_data))
#global file type

<class 'numpy.ndarray'>


In [25]:
a = [1,2,3,4]

In [26]:
print(a)

[1, 2, 3, 4]


In [27]:
print(a[0])

1


In [31]:
print(medical_data.dtype)
#what the values in the array are

float64


In [32]:
print(medical_data.shape)
#row and column

(54, 40)


In [33]:
print('first value in medical data:', medical_data[0,0])
#bc the data is a matrix not linear

first value in medical data: 0.0


In [35]:
print('middle value in medical data:', medical_data[30,20])

middle value in medical data: 6.0


In [36]:
print('first value in medical data:', medical_data[0,0])
med_data_shape = medical_data.shape

first value in medical data: 0.0


In [37]:
print(med_data_shape)

(54, 40)


In [38]:
print(med_data_shape[0])

54


In [39]:
middle_row = int(med_data_shape[0]/2)
middle_col = int(med_data_shape[1]/2)

In [41]:
print('actual/nearest middle value of dataset:', medical_data[middle_row, middle_col])

actual/nearest middle value of dataset: 6.0


In [43]:
print(medical_data[0:4, 0:10])
#index:total number of values included with/after that

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [44]:
bruin = medical_data[:3, 36:]

In [45]:
print(bruin)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [46]:
print('bruin is:\n', bruin)

bruin is:
 [[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [47]:
print(np.mean(medical_data))

5.658333333333333


In [49]:
import time
print(time.ctime())

Mon Jan 27 09:42:29 2020


In [50]:
maxval, minval = np.max(medical_data), np.min(medical_data)
stdval = np.std(medical_data)
print('max:',maxval,', min:',minval,', stdev:',stdval)

max: 19.0 , min: 0.0 , stdev: 4.352194529455482


In [54]:
patient_1 = medical_data[0,:]

In [55]:
print(patient_1)

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [56]:
print('max inflammation for patient 1:', np.max(patient_0))

max inflammation for patient 1: 18.0


In [57]:
patient_2 = medical_data[1,:]
patient_2_min = np.min(patient_2)
print(patient_2_min)

0.0


In [80]:
patient_means = np.mean(medical_data, axis=1)

print(patient_means)
#each patient's mean
#rowwide mean

print(patient_means[0])

[5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1  ]
5.45


In [70]:
#axis = 0 > whatever function for each day (column)
#axis = 1 > whatever function for each patient (row)
patient_means_down = np.mean(medical_data, axis=0)
print(patient_means_down)

[ 0.          0.66666667  1.33333333  2.33333333  2.          1.66666667
  4.33333333  3.66666667  5.          6.          6.          7.
  6.33333333  6.33333333  5.          7.66666667  6.33333333 11.33333333
  9.66666667 11.33333333 14.33333333 10.33333333 11.66666667 11.
  8.66666667  8.66666667  8.66666667  6.          7.66666667  4.33333333
  5.66666667  4.66666667  4.33333333  4.33333333  3.33333333  4.
  1.66666667  2.          0.33333333  0.66666667]


In [71]:
patient_means_down = np.mean(medical_data, axis=0)
print(len(patient_means_down)) 
#length of the array

40


In [72]:
#making a function
def my_func(name): 
    print('Hello', name)

In [73]:
my_func('Shawn')

Hello Shawn


In [74]:
def square_minus(x):
    square = x*x
    square = square - 2
    return (square)

In [81]:
square_minus(4)

14