In [1]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [2]:
print(element[:4])
print(element[4:])
print(element[:]) 

oxyg
en
oxygen


In [3]:
print(element[-1])
print(element[-2])

n
e


In [6]:
print(element[1:-1]) 
#takes the second character (holding a value of 1) and includes all characters except the last one (holding value of -1)

xyge


In [13]:
data[3:3, 4:4]
#empty sting is produced
data[3:3, :]
#empty string because no range of rows are produced with 3:3

NameError: name 'data' is not defined

In [14]:
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

print('B = ')
B = (A[0:1, :3], A[2:3, :3])
print(numpy.vstack(B))

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3]
 [7 8 9]]


In [33]:
npdiff = numpy.array([ 0,  2,  5,  9, 14])
numpy.diff(npdiff)

array([2, 3, 4, 5])

In [34]:
#This function works best on the x-axis because each row is one patient with a series of observations

In [35]:
#The shape of the array would be (59, 40) because only the x-axis is affected by the calculations

In [36]:
#To find the largest change in inflammation, you can sort the values in each row after runnning numpy.diff() and you'll see the value with the greatest change
#It does matter if the change is an increase or decrease, unless you're able to take the absolute value of the differences and then sort.